# 벡터
- 차원: 벡터가 가진 원소의 수
- 방향:
  - 열벡터: 아무런 표시가 없으면 열 방향이라고 가정
  - 행벡터: $W^T$라고 표시
- 원소 수: 길이, 모양

In [ ]:
import numpy as np

asList = [1,2,3]
asArray = np.array(asList) # 방향이 없는 배열
rowVec = np.array([[1,2,3]]) # 행 벡터
colVec = np.array([[1],[2],[3]]) # 열 벡터

print(asArray)
print(rowVec)
print(colVec)

print(f'asList: {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec: {rowVec.shape}') # 차수는 (행, 열)로 표기
print(f'colVec: {colVec.shape}')

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]
asList: (3,)
asArray: (3,)
rowVec: (1, 3)
colVec: (3, 1)


- 벡터의 대수학적 해석: 순서대로 나열된 수 목록
- 벡터의 기하학적 해석: 특정 길이와 방향을 가진 직선
- 벡터의 두점은 꼬리, 머리라고 부른다. 화살표가 있다.
- 기준위치: 원점

## 벡터 연산
- 연산: 벡터를 명사라고 치면 연산은 동사(움직임)라고 볼수 있다.

### 두 벡터의 덧셈, 뺄셈
- 덧셈: 서로 대응되는 원소끼리 더한다. 동일한 차원을 갖는 벡터끼리 가능하다.

$$\begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix} + \begin{bmatrix} 10 \\ 20 \\ 30 \end{bmatrix} = \begin{bmatrix} 14 \\ 25 \\ 36 \end{bmatrix} $$

- 뺄셈: 서로 대응되는 원소끼리 뺀다. 동일한 차원을 갖는 벡터끼리 가능하다.

$$\begin{bmatrix} 4 \\ 5 \\ 6 \end{bmatrix} - \begin{bmatrix} 10 \\ 20 \\ 30 \end{bmatrix} = \begin{bmatrix} -6 \\ -15 \\ -24 \end{bmatrix} $$



In [ ]:
v = np.array([4,5,6])
w = np.array([10,20,30])
u = np.array([0,3,6,9])

vPlusW = v + w
# uPlusW = u + w # 차원이 다르므로 덧셈 불가


In [ ]:
v = np.array([[4,5,6]]) # 행벡터
w = np.array([[10,20,30]]).T # 열벡터

v + w # 차원이 다르면 브로드캐스팅이 적용된다.




array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

- 두 벡터를 기하학적으로 더할땐 벡터 꼬리와 머리를 이어 새로운 벡터를 만든다.
- 모든 벡터의 꼬리와 머리를 계속 이으면 최종 합은 첫번째 꼬리에서 마지막 머리까지 이어지는 선이 된다.
- 기하학적으로 벡터를 빼는 것
  - 두 벡터의 꼬리들을 같은 좌표에 둔다.
  - 뺀 결과의 벡터는 두번째 벡터의 머리에서 첫번째 벡터의 머리로 가는 선이다.
- 벡터의 뺄셈은 기하학적으로 매우 중요한 개념이다. 직교 벡터 분해의 기초이고, 선형 최소제곱법의 기초, 과학과 공학에서 선형대수학의 가장 중요한 응용이다.

### 스칼라-벡터 곱셈
- 스칼라: 벡터나 행렬에 포함된 숫자가 아닌 수 그 자체
- 스칼라와 벡터의 곱은 $\lambda W$으로 나타낼 수 있다.
- 각 벡터 원소에 스칼라를 곱한다.

- 영벡터: 모든 원소가 0인 벡터

In [ ]:
s = 2
a = [3,4,5]
b = np.array(a)
print(a*s) # 파이썬 리스트 별표 연산은 n회 반복한다.
print(b*s)






[3, 4, 5, 3, 4, 5]
[ 6  8 10]


### 스칼라-벡터 덧셈
선형대수학에서 벡터에 스칼라를 더하는 것은 불가능하지만 파이썬에선 가능하다.

In [11]:
s = 2
v = np.array([3,6])
s + v

array([5, 8])

### 스칼라-벡터 곱셈의 기하학적 해석
- 스칼라는 벡터의 방향을 바꾸지 않고 크기만 조정한다.
- 음수를 곱하면 벡터의 방향이 뒤집히지만, 벡터는 원점을 통과해서 양방향으로 무한대로 가는 선을 가르킨다는 해석도 있음
- 벡터의 덧셈과 스칼라-벡터 곱셈을 이용해서 벡터의 평균을 구할 수 있다.
- 벡터의 평균을 구하는 것은 두 벡터를 더하고 스칼라를 1/2로 곱하면 된다.

### 전치(transpose)
- 열벡터를 행벡터, 행벡터를 열벡터로 변환하는 연산
- $m_{i,j}^T = m_{j,i}$
- $V^{TT} = V $

### 벡터 브로드캐스팅
- 현대 컴퓨터 기반 선형대수학에서만 존재한다.
- 한 벡터를 다른 벡터의 각 원소로 연산을 여러번 반복하는 것
$$\begin{bmatrix} 1 & 1 \\ 2 & 2 \\ 3 & 3 \end{bmatrix} + \begin{bmatrix} 10 & 20 \\ 10 & 20 \\ 10 & 20 \end{bmatrix}$$
- 위의 연산과 동일한 결과를 낸다

In [13]:
v = np.array([[1,2,3]]).T # 열벡터
w = np.array([[10,20]]) # 행벡터

v + w


array([[11, 21],
       [12, 22],
       [13, 23]])

## 벡터 크기와 단위 벡터
- 벡터의 크기: 기하학적 길이 또는 노름(norm), 벡터의 꼬리부터 머리까지의 거리
- 유클리드 거리 공식으로 구한다.

$$\begin{Vmatrix} V \end{Vmatrix} = \sqrt{\sum_{i=1}^{n} v^2_i}$$