# 행렬 파트 1
- 큰 행렬은 이미지로 시각화한다.
- 행렬의 각 원소의 수치는 이미지의 색상에 대응


In [4]:
import numpy as np
A = np.arange(60).reshape(6,10)
sub = A[1:4:1, 0:5:1]

print(A)
print(sub)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


## 특수 행렬
### 난수 행렬
- 정규 분포로부터 무작위로 추출된 숫자를 가진 행렬
- 임의의 크기와 계수로 쉽고 빠르게 생성 가능


In [6]:
Mrows = 4
Ncols = 6
A = np.random.randn(Mrows, Ncols)
print(A)


[[ 0.23930103 -0.05966551  0.68228754 -1.05995802 -1.00106965  0.07033839]
 [-0.8789533   0.23894414  0.15079145 -1.5968544   0.82559891  0.10398846]
 [ 0.53393569  0.72907061  1.56709578  0.91630709 -0.84530544 -1.08590735]
 [-0.09013878  0.73116315  0.49309827  0.26923757 -0.57872847 -1.50681427]]



### 정방 행렬(square matrix)과 비정방 행렬(non square matrix)
- 정방 행렬은 행과 열의 수가 같다.
- 비정방 행렬은 행과 열의 수가 다르다.
- 비정방 행렬의 행 수가 많으면 높다, 열 수가 많으면 낣다라고 표현한다.
### 대각 행렬
- 대각(diagonal): 왼쪽 위에서 시작하여 오른쪽 아래로 내려가는 원소들
- 모든 비대각 원소가 0

In [7]:
np.diag(A)

array([0.23930103, 0.23894414, 1.56709578, 0.26923757])


### 삼각 행렬(triangular matrix)
- 주 대각선의 위 또는 아래가 모두 0
- 상삼각 행렬: 0이 아닌 원소가 대각선 위에 있는 경우
- 하삼각 행렬: 0이 아닌 원소가 대각성 아래에 있는 경우

In [9]:
print(np.triu(A))
print(np.tril(A))


[[ 0.23930103 -0.05966551  0.68228754 -1.05995802 -1.00106965  0.07033839]
 [ 0.          0.23894414  0.15079145 -1.5968544   0.82559891  0.10398846]
 [ 0.          0.          1.56709578  0.91630709 -0.84530544 -1.08590735]
 [ 0.          0.          0.          0.26923757 -0.57872847 -1.50681427]]
[[ 0.23930103  0.          0.          0.          0.          0.        ]
 [-0.8789533   0.23894414  0.          0.          0.          0.        ]
 [ 0.53393569  0.72907061  1.56709578  0.          0.          0.        ]
 [-0.09013878  0.73116315  0.49309827  0.26923757  0.          0.        ]]


### 단위 행렬(identity matrix)
- 행렬 또는 벡터에 단위 행렬을 곱하면 동일한 행렬 또는 벡터가 된다. -> 숫자 1과 동등
- 모든 대각 원소가 1인 정방 행렬
- 단위 문자 I

In [11]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 영 행렬(zeros matrix)
- 영 벡터와 유사, 모든 원소가 0
- 단위 문자 0

In [10]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 행렬 수학

### 덧셈과 뺄셈
- 대응 되는 원소끼리 더하고 뺀다
- 크기가 같은 행렬 사이에서만 성립

### 행렬 이동
- 벡터와 마찬가지로 스칼라를 더할 수 없다
- 정방 행렬에 스칼라를 더하면 행렬 이동(shifting a matrix)이다
- 단위 행렬에 스칼라를 곱해서 더한다.

$A+\lambda{I}$

In [14]:
A = np.array([[4,5,1], [0,1,11], [4,9,7]])
s=6
print(A + s) # 이동이 아님

print(A + s*np.eye(len(A))) # 이동


[[10 11  7]
 [ 6  7 17]
 [10 15 13]]
[[10.  5.  1.]
 [ 0.  7. 11.]
 [ 4.  9. 13.]]


### 스칼라 곱셈과 아다마르곱
- 행렬의 각 원소에 동일한 스칼라를 곱한다.
- 아다마르곱도 두 행렬을 요소별로 곱한다.
- 아다마르곱은 여러 주제에서 사용되고, 역행렬 계산에 사용된다.

In [20]:
A = np.random.randn(3,4)
B = np.random.randn(3,4)
print(A*B) # 아다마르곱
print(np.multiply(A,B)) # 아다마르곱
print(A@B.T) # 행렬 곱셈

[[-0.06374286  0.23919045 -0.20973647 -0.00629052]
 [-0.09459022  0.1861153   1.30216069 -0.2249888 ]
 [ 1.54197735 -0.4748691  -0.3011552   0.97054448]]
[[-0.06374286  0.23919045 -0.20973647 -0.00629052]
 [-0.09459022  0.1861153   1.30216069 -0.2249888 ]
 [ 1.54197735 -0.4748691  -0.3011552   0.97054448]]
[[-0.04057941  0.02615169  0.78878289]
 [-0.46945988  1.16869696 -1.03128956]
 [ 1.18969139  1.2682953   1.73649754]]


## 표준 행렬 곱셈(matrix multiplication)
- 표준 행렬 곱셈은 원소별이 아닌 행과 열 단위로 동작
- 표준이라는 단어는 아다마르곱, 스칼라 곱셈과 구별하기 위함
- 행렬 곱이 가능한지 여부는 두 행렬의 크기가 서로 짝이 맞을때 가능

### 유효성 규칙
- M x N * N x K = M x K
- 내부 차원의 수가 일치할때 유효하고 외부 차원의 수로 정의된다
- 일반적인 교환 법칙을 따르지 않는다.
- 행렬곱은 아무 기호 없이 AB 로 표현한다.

### 행렬 곱셈
- 